# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.sift.insure:
    container_name: orderer.sift.insure
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /media/data/blockchain/orderer:/var/hyperledger/production
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/sift.insure/orderers/orderer.sift.insure/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/sift.insure/orderers/orderer.sift.insure/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.sift.insure:
    container_name: peer0.sift.insure
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.sift.insure
      - CORE_PEER_ADDRESS=peer0.sift.insure:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sift.insure:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /media/data/blockchain/peer0.sift.insure:/var/hyperledger/production
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sift.insure/peers/peer0.sift.insure/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sift.insure/peers/peer0.sift.insure/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer1.sift.insure:
    container_name: peer1.sift.insure
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.sift.insure
      - CORE_PEER_ADDRESS=peer1.sift.insure:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.sift.insure:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sift.insure:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /media/data/blockchain/peer1.sift.insure:/var/hyperledger/production
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sift.insure/peers/peer1.sift.insure/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sift.insure/peers/peer1.sift.insure/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053

  peer0.aig.com:
    container_name: peer0.aig.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.aig.com
      - CORE_PEER_ADDRESS=peer0.aig.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.aig.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.aig.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /media/data/blockchain/peer0.aig.com:/var/hyperledger/production
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/aig.com/peers/peer0.aig.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/aig.com/peers/peer0.aig.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer1.aig.com:
    container_name: peer1.aig.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.aig.com
      - CORE_PEER_ADDRESS=peer1.aig.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.aig.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.aig.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /media/data/blockchain/peer1.aig.com:/var/hyperledger/production
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/aig.com/peers/peer1.aig.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/aig.com/peers/peer1.aig.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
