version: '3.7'

services:
  composer-rest-server:
    container_name: siftledger-composer-reset-server
    image: siftledger/compoer-reset-server:latest
    build:
      context: ../
      dockerfile:  ./composer-rest-server/Dockerfile
    volumes:
      - "~/.composer:/home/composer/.composer"
    restart: always
    networks:
      - insure2go-network

networks:
  insure2go-network:
    driver: bridge
