version: '3.7'

services:
  composer-rest-server:
    container_name: siftledger-composer-rest-server
    image: siftledger/composer-rest-server:latest
    build:
      context: ../
      dockerfile:  ./composer-rest-server/Dockerfile
    volumes:
      - "~/.composer:/home/composer/.composer"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - insure2go-network

networks:
  insure2go-network:
    driver: bridge
