version: '3.7'

services:
  composer-rest-server:
    container_name: siftledger-composer-rest-server
    image: siftledger/composer-rest-server:latest
    build:
      context: ../
      dockerfile:  ./docker/Dockerfile
    volumes:
      - "~/.composer:/home/composer/.composer"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - insure2go-network

  composer-rest-server-auth:
    container_name: siftledger-composer-rest-server-auth
    image: siftledger/composer-rest-server-auth:latest
    build:
      context: ../
      dockerfile:  ./auth/docker/Dockerfile
    volumes:
      - "/media/data/composer-rest-server-auth.log:/app/composer-rest-server-auth.log"
    ports:
      - "3001:3001"
    environment:
      - COMPOSER_AUTH_DOMAIN=http://composer-rest-server:3000
    restart: always
    networks:
      - insure2go-network
networks:
  insure2go-network:
    driver: bridge
